### ISSUE TITLE
Cannot get scss files work as expected

### ISSUE THREAD

**Issue by diegoferigo** [envygeeks/jekyll-assets#485]
- [x] I tried updating to the latest version.
- [x] I Am on Linux

## Description

Probably I miss something (3.x documentation still needs improvements), but I cannot get `scss` files working as with the previous release.

I understood that now, given a file `_assets/css/blog.css`, instead of using:

```
{% css blog %}
```

I have to use:

```
{% asset blog %}
```

However, I cannot port 1:1 this logic to `scss`. Given a file `_assets/scss/blog.scss`, what is the correct way to compile it to css and get both the html and the url?

##### HTML `{% asset blog %}`

No output

##### URL `{% asset blog @path %}` 

The `scss` file is not compiled. Instead, it is copied to the `_site/assets` folder and its link is used, generating:

```
@import url("/assets/blog-....scss");
```

##### HTML `{% asset blog.css %}`, URL `{% asset blog.css @path %}`

In both cases I get this error:

```
  Liquid Exception: no implicit conversion of nil into String in /_layouts/bootstrap-default.html
             Error: no implicit conversion of nil into String
             Error: Run jekyll build --trace for more information.
```

What am I doing wrong?

## Additional informations

`Gemfile.lock`

```GIT
  remote: https://github.com/diegoferigo/jekyll-jupyter-notebook.git
  revision: dd0757137257e03f3ea67f644af5733bbaf6e32f
  branch: customCSS
  specs:
    jekyll-jupyter-notebook (0.0.2)
      jekyll

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    autoprefixer-rails (7.2.4)
      execjs
    bootstrap (4.0.0.beta3)
      autoprefixer-rails (>= 6.0.3)
      popper_js (>= 1.12.3, < 2)
      sass (>= 3.5.2)
    colorator (1.1.0)
    concurrent-ruby (1.0.5)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.5)
    execjs (2.7.0)
    extras (0.3.0)
      forwardable-extended (~> 2.5)
    fastimage (2.1.1)
    ffi (1.9.18)
    forwardable-extended (2.6.0)
    htmlbeautifier (1.3.1)
    htmlcompressor (0.4.0)
    http_parser.rb (0.6.0)
    i18n (0.9.1)
      concurrent-ruby (~> 1.0)
    jekyll (3.7.0)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 0.7)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 1.14)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (>= 1.7, < 4)
      safe_yaml (~> 1.0)
    jekyll-assets (3.0.5)
      activesupport (~> 5.0)
      execjs (~> 2.7)
      extras (~> 0.2)
      fastimage (~> 2.0, >= 1.8)
      jekyll (>= 3.5, < 4.0)
      jekyll-sanity (~> 1.2)
      liquid-tag-parser (~> 1.0)
      nokogiri (~> 1.8)
      pathutil (~> 0.16)
      sprockets (>= 3.3, < 4.1.beta)
    jekyll-feed (0.9.2)
      jekyll (~> 3.3)
    jekyll-sanity (1.2.0)
      jekyll (~> 3.1)
    jekyll-sass-converter (1.5.1)
      sass (~> 3.4)
    jekyll-theme-clean-blog (0.1.1)
      jekyll (~> 3.6)
    jekyll-tidy (0.2.2)
      htmlbeautifier
      htmlcompressor
      jekyll
    jekyll-watch (2.0.0)
      listen (~> 3.0)
    kramdown (1.16.2)
    liquid (4.0.0)
    liquid-tag-parser (1.8.0)
      extras (~> 0.3)
      liquid (>= 3.0, < 5.0)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    mercenary (0.3.6)
    mini_portile2 (2.3.0)
    minima (2.1.1)
      jekyll (~> 3.3)
    minitest (5.11.1)
    nokogiri (1.8.1)
      mini_portile2 (~> 2.3.0)
    pathutil (0.16.1)
      forwardable-extended (~> 2.6)
    popper_js (1.12.9)
    public_suffix (3.0.1)
    rack (2.0.3)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rouge (3.1.0)
    ruby_dep (1.5.0)
    safe_yaml (1.0.4)
    sass (3.5.5)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sprockets (4.0.0.beta6)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    thread_safe (0.3.6)
    tzinfo (1.2.4)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap
  jekyll-assets
  jekyll-feed (~> 0.6)
  jekyll-jupyter-notebook!
  jekyll-theme-clean-blog
  jekyll-tidy
  minima (~> 2.0)
  tzinfo-data

BUNDLED WITH
   1.15.4
```

`jekyll-assets configuration`
```yaml
assets:
  compress:
    js: true
    css: true
  prefix: /assets
  features:
    liquid: true
  digest: true
  source_maps: false
  sources:
    - _assets/scss
    - _vendor/bundle/ruby/2.3.0/gems/bootstrap-4.0.0.beta/assets/javascripts/
    - _vendor/bundle/ruby/2.3.0/gems/popper_js-1.11.1/assets/javascripts/
```

**Comment by lucasrenan** [comment]
@diegoferigo by any chance are you using the gem `jekyll-bootstrap-sass`? I'm experiencing the same problem here.

**Comment by envygeeks** [comment]
If you wish bootstrap you should do it properly by using `bootstrap-sass` or `bootstrap`.  We have no plans to integrate with `jekyll-bootstrap-sass`, and probably never will, since we integrate directly with Bootstrap's official gems, which intern automatically integrate with us because of Sprockets.

As for the original ticket, if the documentation needs improvement point it out, comments like yours make no sense, I have no idea what you find confusing about the documentation, I am not you, and I do not wish to take a guess.  That said, we do not support `{% asset blog %}` anymore, you must either provide `{% asset blog.css %}` to get the compiled form or `{% asset blog.scss %}` to get the uncompiled form.  This is noted as a rational for removal of the old tags, and is required by Sprockets now to find an asset.  As for the error you get when you do that, please run with `--trace` and determine if the error originates from us directly, from your SCSS, or from your own plugins/Liquid.

**Comment by diegoferigo** [comment]
@lucasrenan Nope, the `Gemfile.lock` contains all the gems I'm using right now. For bootstrap I use the official `bootstrap (4.0.0.beta3)` gem. However, I don't think this is related to bootstrap gems. For sure there is some rationale about the new `jekyll-asset` version I'm still missing, and I guess the error is related either to our configuration (very likely) or an internal bug.

@envygeeks 
So if I got correctly my `Experiment #2` should be correct. Here below you can find the trace:

```
  Liquid Exception: no implicit conversion of nil into String in /_layouts/bootstrap-default.html
/srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/path_utils.rb:111:in `initialize': no implicit conversion of nil into String (TypeError)
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/path_utils.rb:111:in `new'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/path_utils.rb:111:in `relative_path_from'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/source_map_utils.rb:52:in `block in format_source_map'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/source_map_utils.rb:48:in `map'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/source_map_utils.rb:48:in `format_source_map'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/sass_processor.rb:83:in `call'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/sass_processor.rb:32:in `call'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:84:in `call_processor'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `reverse_each'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `call_processors'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:33:in `call'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:84:in `call_processor'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `reverse_each'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `call_processors'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/loader.rb:144:in `load_from_unloaded'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/loader.rb:59:in `block in load'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/loader.rb:43:in `load'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/cached_environment.rb:44:in `load'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/bundle.rb:27:in `call'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:84:in `call_processor'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `reverse_each'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `call_processors'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/loader.rb:144:in `load_from_unloaded'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/loader.rb:59:in `block in load'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/loader.rb:43:in `load'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/cached_environment.rb:44:in `load'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-assets-3.0.5/lib/jekyll/assets/patches/cached.rb:47:in `find_asset!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/environment.rb:35:in `find_asset!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-assets-3.0.5/lib/jekyll/assets/tag.rb:160:in `internal'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-assets-3.0.5/lib/jekyll/assets/tag.rb:58:in `render_raw'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-assets-3.0.5/lib/jekyll/assets/tag.rb:73:in `render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/tags/include.rb:139:in `block in render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/tags/include.rb:136:in `render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/renderer.rb:123:in `render_liquid'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/renderer.rb:188:in `render_layout'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/renderer.rb:155:in `place_in_layouts'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/renderer.rb:85:in `render_document'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/renderer.rb:62:in `run'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:453:in `block (2 levels) in render_docs'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:451:in `each'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:451:in `block in render_docs'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:450:in `each_value'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:450:in `render_docs'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:190:in `render'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:73:in `process'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/command.rb:28:in `process_site'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/commands/build.rb:65:in `build'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/commands/build.rb:36:in `process'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/commands/serve.rb:93:in `each'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/commands/serve.rb:93:in `start'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.0/exe/jekyll:15:in `<top (required)>'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/bin/jekyll:22:in `load'
        from /srv/jekyll/www/_vendor/bundle/ruby/2.3.0/bin/jekyll:22:in `<main>'
```

About the documentation, it took me a while to figure out the correct usage, and this means something. Eventually as you pointed out I found what looks the correct usage, but it was not straightforward. For instance, can you please point out where this logic is documented?

**Comment by envygeeks** [comment]
It's an internal bug more than likely, based on the pathing of the error I can deduce you can probably keep using Jekyll-Assets without error from here on out until I can look into the bug by disabling source maps (which is an experimental feature that is mostly stable but sometimes errors out depending on what's going on around it.)

**Comment by diegoferigo** [comment]
As my first posts, if you mean setting `source_maps: false`, this is already the case.

**Comment by envygeeks** [comment]
Ha, thanks for the headsup on that.  I looked at the error again, this error actually originates directly from Sprockets and has little to do with us (if anything at all.) Unfortunately disabling source maps only affects us writing them, cleaning them up, parsing the file mappings, but past that it doesn't really affect Sprockets, who does their own Source Mapping (we do use it to write the source maps but they process 100% of the time.). If your site is open source then I can see for sure where it originates, if it is not open source you'll have to provide a repository to replicate it, but until I can determine where exactly from the stack it originates from, I'm hinging on saying file this upstream as it mostly ships from within their source.

**Comment by diegoferigo** [comment]
Thanks for you help so far. I'm not so proficient yet in web developing and figuring out all the features all these tools provide is still not straightforward. The website project is still at its infancy, and you can find a working version [here](https://github.com/loc2/jekyll-template).

What I did from the current status is just:

- Update all the gems
- Configure `jekyll-assets` as reports the first post
- Try to port the current demo theme to the new version. In particular editing as described in the first post an [html file](https://github.com/loc2/jekyll-template/blob/master/jekyll/_includes/bootstrap-head.html#L11) and a [scss](https://github.com/loc2/jekyll-template/blob/master/jekyll/assets/custom.css).

**Comment by Jacksthelad** [comment]
@diegoferigo I was having the same issue with my {% css %} and {% js %} files until I read your issue, so thanks.

@envygeeks thanks for a great project. I was having trouble with the documentation too. it was mainly because there was nothing explicitly explaining how to access directories within the _assets file. I have a js file and a css file both with the name "main" (not ideal, but I inherited the project) within two separate directories under _assets and I couldn't understand how to differentiate between the two until I read this. maybe a couple of examples may help? thanks again :+1:

**Comment by envygeeks** [comment]
Your issue is unrelated to this issue @Jacksthelad.  Please file a pull request if you would like the documentation updated because you found it confusing, as this is a one in 300K issue.

**Comment by envygeeks** [comment]
I'm pushing this error upstream because it belongs to them from the looks of it after double checking.

**Comment by xaralis** [comment]
Any updates on this? It seems I'm having the same problem and I'm kinda stuck here. Any help or workaround would be highly appreciated.
