### ISSUE TITLE
Unknown compressor: jekyll_assets_scss

### ISSUE THREAD

**Issue by maedi** [envygeeks/jekyll-assets#505]
- [x] I tried updating to the latest version.
- [X] I Am on macOS

## Description

After updating Jekyll from 3 to 3.6/3.7 I can't run `jekyll serve` without getting the following output.

## Output

```sh
$ jekyll serve
 <...>
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.7.3 | Error:  unknown compressor: jekyll_assets_scss
```

## Config

```ruby
gem "jekyll-assets", git: "https://github.com/envygeeks/jekyll-assets"
gem "sprockets", "~> 4.0.beta", {
  require: false
}
gem "image_optim"
gem "image_optim_pack"
gem "uglifier"
```

**Comment by envygeeks** [comment]
Please provide the full trace, thanks!

**Comment by maedi** [comment]
You mean this?
```sh
$ jekyll serve --verbose
  Logging at level: debug
Configuration file: /Users/maedi/Sites/cluejar.com/_config.yml
  Logging at level: debug
         Requiring: jekyll-mentions
         Requiring: jekyll-feed
         Requiring: jekyll-sitemap
         Requiring: jekyll-gist
         Requiring: jekyll-redirect-from
         Requiring: jekyll-assets
            Source: /Users/maedi/Sites/cluejar.com
       Destination: /Users/maedi/Sites/cluejar.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       EntryFilter: excluded /LICENSE
       EntryFilter: excluded /CNAME
       EntryFilter: excluded /README.md
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
           Reading: _posts/2016-10-27-experience-at-spiel.md
           Reading: _posts/2018-1-2-bitmap-fonts-indesign.md
           Reading: _posts/2017-07-16-how-i-made-delivery-duck.md
           Reading: _events/2017/hogs-birthday-2017.md
           Reading: _events/2017/pax-2017.md
           Reading: _events/2018/pax-2018.md
           Reading: _events/2016/spiel-2016.md
           Reading: _features/mobile-game/2-vehicles.md
           Reading: _features/mobile-game/1-mechanics.md
           Reading: _features/mobile-game/3-cargo.md
           Reading: _features/mobile-game/4-levels.md
           Reading: _features/board-game/3-terrain.md
           Reading: _features/board-game/4-vehicles.md
           Reading: _features/board-game/2-players.md
           Reading: _features/board-game/1-mechanics.md
           Reading: _games/gift.md
           Reading: _games/delivery-duck/mobile-game.md
           Reading: _games/delivery-duck/board-game.md
           Assets:  messaging hooks on before_merge through config
           Assets:  messaging hooks on before_init through env
           Assets:  messaging hooks on after_init through env
jekyll 3.7.3 | Error:  unknown compressor: jekyll_assets_scss
```

**Comment by devraj** [comment]
```
iMac:jekyll-foundation devraj$ bundle exec jekyll serve --trace --verbose
  Logging at level: debug
Configuration file: /Users/devraj/Work/Frameworks/jekyll-foundation/_config.yml
  Logging at level: debug
            Source: ./_source
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       EntryFilter: excluded /README.md
       EntryFilter: excluded /README.md
           Reading: _interfaces/sample.haml
           Assets:  messaging hooks on before_merge through config
           Assets:  messaging hooks on before_init through env
           Assets:  messaging hooks on after_init through env
bundler: failed to load command: jekyll (/Users/devraj/.rbenv/versions/2.3.1/bin/jekyll)
Sprockets::Error: unknown compressor: jekyll_assets_scss
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/compressing.rb:55:in `css_compressor='
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/compressors/scss.rb:26:in `block in <module:Compressors>'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/env.rb:61:in `instance_eval'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/env.rb:61:in `block in initialize'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/hook.rb:100:in `block in trigger'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/hook.rb:99:in `map'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/hook.rb:99:in `trigger'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/env.rb:60:in `initialize'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets.rb:24:in `new'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets.rb:24:in `block in <top (required)>'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:103:in `block in trigger'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:102:in `each'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:102:in `trigger'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:165:in `read'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:71:in `process'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `block in start'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `each'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `start'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
  /Users/devraj/.rbenv/versions/2.3.1/bin/jekyll:23:in `load'
  /Users/devraj/.rbenv/versions/2.3.1/bin/jekyll:23:in `<top (required)>'iMac:jekyll-foundation devraj$ bundle exec jekyll serve --trace --verbose
  Logging at level: debug
Configuration file: /Users/devraj/Work/Frameworks/jekyll-foundation/_config.yml
  Logging at level: debug
            Source: ./_source
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       EntryFilter: excluded /README.md
       EntryFilter: excluded /README.md
           Reading: _interfaces/sample.haml
           Assets:  messaging hooks on before_merge through config
           Assets:  messaging hooks on before_init through env
           Assets:  messaging hooks on after_init through env
bundler: failed to load command: jekyll (/Users/devraj/.rbenv/versions/2.3.1/bin/jekyll)
Sprockets::Error: unknown compressor: jekyll_assets_scss
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-4.0.0.beta6/lib/sprockets/compressing.rb:55:in `css_compressor='
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/compressors/scss.rb:26:in `block in <module:Compressors>'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/env.rb:61:in `instance_eval'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/env.rb:61:in `block in initialize'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/hook.rb:100:in `block in trigger'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/hook.rb:99:in `map'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/hook.rb:99:in `trigger'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets/env.rb:60:in `initialize'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets.rb:24:in `new'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/jekyll-assets-be236f4e93ca/lib/jekyll/assets.rb:24:in `block in <top (required)>'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:103:in `block in trigger'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:102:in `each'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:102:in `trigger'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:165:in `read'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:71:in `process'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `block in start'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `each'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `start'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/devraj/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
  /Users/devraj/.rbenv/versions/2.3.1/bin/jekyll:23:in `load'
  /Users/devraj/.rbenv/versions/2.3.1/bin/jekyll:23:in `<top (required)>'
```

**Comment by devraj** [comment]
@envygeeks @maedi I have narrowed it down to the fact that it's a change on the master branch, `3.0.7` works perfectly fine with the following `Gemfile` source available at http://github.com/anomaly/jekyll-foundation 
```
source 'https://rubygems.org'

gem 'jekyll'
gem 'uglifier'
gem 'rouge'
gem 'autoprefixer-rails'
gem "sprockets", "~> 4.0.beta", {
  require: false
}

group :jekyll_plugins do
    gem 'jekyll-assets'
    gem 'jekyll-watch'
    gem 'jekyll-haml'
    gem 'jekyll-faker'
    gem 'jekyll-reload'
    gem 'jekyll-cache'
    gem 'jekyll-incremental'
    gem 'jekyll-menus'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```
you should be able to check out that repo and add change the reference of `Jekyll-Assets` to `gem 'jekyll-assets', :git => 'https://github.com/envygeeks/jekyll-assets.git', :branch => 'master'` and reproduce the issue.

Hope this helps.
