### ISSUE TITLE
Incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by abevoelker** [envygeeks/jekyll-assets#522]
- [ ] I tried updating to the latest version.
  - [x] I can't, there is an issue.

Gem `github-pages` is incompatible with the latest git version of this gem:

```console
$ bundle
Fetching https://github.com/envygeeks/jekyll-assets
Fetching gem metadata from https://rubygems.org/..............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 4.2.9)

  In Gemfile:
    github-pages was resolved to 180, which depends on
      activesupport (= 4.2.9)

    jekyll-assets was resolved to 3.0.8, which depends on
      activesupport (~> 5.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [x] I Am on Linux
- [ ] I Am on macOS

## Steps

```console
$ git clone https://github.com/abevoelker/jekyll-assets-repro.git
$ bundle
$ bundle exec jekyll serve --trace
```

## Output

```console
$ bundle exec jekyll serve --trace
Configuration file: /tmp/foo/_config.yml
            Source: /tmp/foo
       Destination: /tmp/foo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT in /tmp/foo/_posts/2018-03-27-welcome-to-jekyll.markdown
bundler: failed to load command: jekyll (/home/abe/.gem/ruby/2.5.0/bin/jekyll)
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:103:in `join'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:103:in `render'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
  /home/abe/.gem/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:123:in `render_liquid'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:76:in `render_document'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:62:in `run'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:462:in `block (2 levels) in render_docs'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:460:in `each'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:460:in `block in render_docs'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:459:in `each_value'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:459:in `render_docs'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:190:in `render'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:73:in `process'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `block in start'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `each'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `start'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/abe/.gem/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /home/abe/.gem/ruby/2.5.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
  /home/abe/.gem/ruby/2.5.0/bin/jekyll:23:in `load'
  /home/abe/.gem/ruby/2.5.0/bin/jekyll:23:in `<top (required)>'
```

## Expected

I expected an `<img>` tag in my post. If I trap the error it looks like it's trying to directly output the binary image data into the blog post:

![screenshot from 2018-03-28 00-10-54](https://user-images.githubusercontent.com/153459/38009988-9111cba4-321c-11e8-8128-093087c971fb.png)

**Comment by abevoelker** [comment]
I unpacked all the gems that `gh-pages` comes with and did some binary search elimination, and the issue can also be reproduced with this Gemfile:

```ruby
source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 3.7.3"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
#gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?

gem "jekyll-assets", group: :jekyll_plugins


# this breaks jekyll-assets:
gem "jekyll-mentions", "1.3.0"
```

So the issue seems to be coming from an incompatibility with the `jekyll-mentions` gem.

**Comment by envygeeks** [comment]
The UTF-8 ASCII bug belongs to Liquid or Jekyll.  The ActiveSupport issue is a WONTFIX. Please file a bug on the respective repository and ask them to upgrade.  I will not be downgrading to support older gems with slower development cycles sadly.

**Comment by abevoelker** [comment]
Okie doke
