### ISSUE TITLE
jekyll-assets 3.0.9 reports NameError

### ISSUE THREAD

**Issue by xu-cheng** [envygeeks/jekyll-assets#530]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
- [x] I Am on macOS
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported.

## Description

After upgrading to jekyll-assets 3.0.9, my website cannot be built. Instead, it reports
```
NameError: undefined local variable or method `path' for #<Jekyll::Assets::Env:0x00007facc2237b68>
Did you mean?  paths
```

## Output

```
NameError: undefined local variable or method `path' for #<Jekyll::Assets::Env:0x00007facc2237b68>
Did you mean?  paths
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets/utils.rb:82:in `block (2 levels) in raw_precompiles'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets/utils.rb:74:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets/utils.rb:74:in `block in raw_precompiles'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets/utils.rb:63:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets/utils.rb:63:in `each_with_object'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets/utils.rb:63:in `raw_precompiles'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets/env.rb:164:in `copy_raw!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets/env.rb:59:in `initialize'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets.rb:24:in `new'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-3.0.9/lib/jekyll/assets.rb:24:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:103:in `block in trigger'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:102:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:102:in `trigger'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:165:in `read'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:71:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
```

# The cause 

In 
https://github.com/envygeeks/jekyll-assets/blob/789e78d2b708e4b843ae02eda259dc72b30c562f/lib/jekyll/assets/utils.rb#L74-L86

`src: path` should be `src: p`

**Comment by envygeeks** [comment]
v3.0.10 has been pushed with a hotfix. Thanks for the report.

**Comment by xu-cheng** [comment]
Thanks for the quick fix.
