### ISSUE TITLE
Sprockets 4 beta breaks jekyll-assets

### ISSUE THREAD

**Issue by amyspark** [envygeeks/jekyll-assets#589]
- [X] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [X] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [X] I am on macOS 10.13
- [ ] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Description

https://github.com/rails/sprockets/pull/560 (i.e. Sprockets 4 beta 9) breaks jekyll-assets because it adds a new parameter to the manifest finding logic.

## Steps

1. Add `jekyll-assets` from git to your Gemfile. (I need master because of Jekyll 4.)
2. `bundle update` Sprockets from `4.0.0.beta8` to `4.0.0.beta9`.
3. Run `jekyll build`.

## Output

This is part of a Yarn and Gulp-based workflow.

```bash

[22:10:59] Starting 'jekyll:prod'...
Configuration file: /Users/amalia/Desktop/blog/_config.yml
Configuration file: /Users/amalia/Desktop/blog/_config-prod.yml
            Source: /Users/amalia/Desktop/blog
       Destination: /Users/amalia/Desktop/blog/public
 Incremental build: enabled
      Generating... 
bundler: failed to load command: jekyll (/Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bin/jekyll)
ArgumentError: wrong number of arguments (given 2, expected 1)
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bundler/gems/jekyll-assets-c1036a60811f/lib/jekyll/assets/manifest.rb:46:in `find_directory_manifest'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/sprockets-4.0.0.beta9/lib/sprockets/manifest.rb:56:in `initialize'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bundler/gems/jekyll-assets-c1036a60811f/lib/jekyll/assets/manifest.rb:29:in `initialize'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bundler/gems/jekyll-assets-c1036a60811f/lib/jekyll/assets/env.rb:36:in `new'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bundler/gems/jekyll-assets-c1036a60811f/lib/jekyll/assets/env.rb:36:in `initialize'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bundler/gems/jekyll-assets-c1036a60811f/lib/jekyll/assets.rb:70:in `new'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bundler/gems/jekyll-assets-c1036a60811f/lib/jekyll/assets.rb:70:in `block in read_hook!'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/hooks.rb:102:in `block in trigger'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/hooks.rb:101:in `each'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/hooks.rb:101:in `trigger'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/site.rb:176:in `read'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/site.rb:74:in `process'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/command.rb:28:in `process_site'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/commands/build.rb:65:in `build'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/commands/build.rb:36:in `process'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/command.rb:89:in `each'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/gems/jekyll-4.0.0.pre.alpha1/exe/jekyll:15:in `<top (required)>'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bin/jekyll:23:in `load'
  /Users/amalia/Desktop/blog/vendor/bundle/ruby/2.5.0/bin/jekyll:23:in `<top (required)>'
[22:11:00] 'jekyll:prod' errored after 1.36 s
```

## Expected

```bash
[22:23:05] Starting 'jekyll:prod'...
Configuration file: /Users/amalia/Desktop/blog/_config.yml
Configuration file: /Users/amalia/Desktop/blog/_config-prod.yml
            Source: /Users/amalia/Desktop/blog
       Destination: /Users/amalia/Desktop/blog/public
 Incremental build: enabled
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 1.887 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
[22:23:08] Finished 'jekyll:prod' after 3.13 s
```

**Comment by envygeeks** [comment]
I just wanted to update this ticket and let you know that I did indeed get hold of Sprockets core team and this is an unintended signature change, I'll be working with them over the next few weeks to fix this issue, or if they discover that they wish it not to break, update Jekyll-Assets.

**Comment by envygeeks** [comment]
Sprockets is at 4.x on the master branch and testing is passing.
