### ISSUE TITLE
undefined method `asset_path'

### ISSUE THREAD

**Issue by chalmagean** [envygeeks/jekyll-assets#635]
Hi, I keep getting this error, and I'm not sure why.

I don't get it all the time, but most of the time it's there.

```
[SassC::FunctionsHandler] undefined method `asset_path' for #<#<Class:0x00007fb5b065aca8>:0x00007fb5b065a0f0>
                    ------------------------------------------------
      Jekyll 4.0.0   Please append `--trace` to the `build` command
                     for any additional information or backtrace.
                    -----------------------------------------------
```

Here's the trace.

```
[SassC::FunctionsHandler] undefined method `asset_path' for #<#<Class:0x00007fe0830e97d0>:0x00007fe0830e9528>
Traceback (most recent call last):
	46: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
	45: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	44: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	43: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	42: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	41: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	40: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/promise.rb:563:in `block in realize'
	39: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
	38: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
	37: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
	36: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
	35: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
	34: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
	33: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/base.rb:88:in `find_all_linked_assets'
	32: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-63f8aa316574/lib/jekyll/assets/patches/cached_environment.rb:37:in `block (2 levels) in <module:CachedEnvironment>'
	31: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/base.rb:81:in `find_asset'
	30: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
	29: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
	28: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
	27: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `block in load'
	26: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
	25: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
	24: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
	23: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
	22: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
	21: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/bundle.rb:27:in `call'
	20: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
	19: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
	18: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
	17: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `block in load'
	16: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
	15: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
	14: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
	13: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
	12: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
	11: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:33:in `call'
	10: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
	 9: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
	 8: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
	 7: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
	 6: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
	 5: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:31:in `call'
	 4: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:58:in `call'
	 3: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/utils.rb:138:in `module_include'
	 2: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:59:in `block in call'
	 1: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/sassc-2.2.1/lib/sassc/engine.rb:49:in `render'
/Users/myuser/Work/blog/_assets/stylesheets/vendor/open-iconic-bootstrap.scss:6: Error: error in C function asset_path: undefined method `asset_path' for #<#<Class:0x00007fe0830e97d0>:0x00007fe0830e9528> (SassC::SyntaxError)
        on line 6:194 of _assets/stylesheets/vendor/open-iconic-bootstrap.scss, in function `asset_path`
        from line 6:194 of _assets/stylesheets/vendor/open-iconic-bootstrap.scss
        from line 23:9 of _assets/stylesheets/main.scss
>> pen-iconic.ttf')) format('truetype'), url(asset_path('open-iconic.svg#iconic

```

**Comment by envygeeks** [comment]
Hey @chalmagean can you try the master branch and see if this is still an issue?

**Comment by chalmagean** [comment]
Not sure if it's related but now I'm getting the following when I try to build my site for production.


```
/Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/plugins/html/defaults/img.rb:40:in `set_integrity': undefined method `update' for #<Liquid::Tag::Parser:0x00007fc2fb35b018> (NoMethodError)
```

I see that jekyll-assets depends on liquid-tag-parser 1.0.0, and they are now at 1.9.

**Comment by envygeeks** [comment]
"They're" would be me as that's my library.  Jekyll-Assets relies on `~> 1.0` not `= 1.0.0` so you can run bundle update any time you please to get any version of that dependency within the 1.x semantic range. Please provide a proper trace, not just the error, I can do nothing with an error, thanks!

**Comment by chalmagean** [comment]
Sorry, I didn't realize that.

```
JEKYLL_ENV=production jekyll b --trace
Configuration file: /Users/myuser/Work/blog/_config.yml
            Source: /Users/myuser/Work/blog
       Destination: /Users/myuser/Work/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
  Liquid Exception: undefined method `update' for #<Liquid::Tag::Parser:0x00007ff36d483790> in /Users/myuser/Work/blog/_posts/2014-11-11-how-i-create-a-new-rails-project.md
Traceback (most recent call last):
	50: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bin/ruby_executable_hooks:24:in `<main>'
	49: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bin/ruby_executable_hooks:24:in `eval'
	48: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bin/jekyll:23:in `<main>'
	47: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bin/jekyll:23:in `load'
	46: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	45: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	44: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	43: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	42: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	41: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	40: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	39: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	38: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	37: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	36: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
	35: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
	34: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
	33: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
	32: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:201:in `render'
	31: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `render_docs'
	30: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `each_value'
	29: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `block in render_docs'
	28: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `each'
	27: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
	26: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
	25: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
	24: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:80:in `render_document'
	23: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:127:in `render_liquid'
	22: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:32:in `render!'
	21: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
	20: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:33:in `block in render!'
	19: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:53:in `measure_bytes'
	18: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:34:in `block (2 levels) in render!'
	17: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_counts'
	16: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:35:in `block (3 levels) in render!'
	15: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	14: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	13: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	12: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	11: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	10: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	 9: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/tag.rb:63:in `render'
	 8: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/tag.rb:51:in `render_raw'
	 7: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/tag.rb:158:in `internal'
	 6: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/default.rb:42:in `set'
	 5: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/default.rb:42:in `each'
	 4: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/default.rb:47:in `block in set'
	 3: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/default.rb:81:in `run'
	 2: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/default.rb:81:in `each'
	 1: from /Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/default.rb:82:in `block in run'
/Users/myuser/.rvm/gems/ruby-2.6.3@blog_jkl/bundler/gems/jekyll-assets-3c371cf3fa5f/lib/jekyll/assets/plugins/html/defaults/img.rb:40:in `set_integrity': undefined method `update' for #<Liquid::Tag::Parser:0x00007ff36d483790> (NoMethodError)
```

**Comment by envygeeks** [comment]
Hmmm... that makes the error very clear!
