### ISSUE TITLE
[SassC::FunctionsHandler] undefined method `asset_path'

### ISSUE THREAD

**Issue by chalmagean** [envygeeks/jekyll-assets#640]
Hi, I get the following exception. I'm using the latest version from master.

```
✗ jekyll s --trace
Configuration file: /Users/me/Work/myblog/_config.yml
            Source: /Users/me/Work/myblog
       Destination: /Users/me/Work/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
[SassC::FunctionsHandler] undefined method `asset_path' for #<#<Class:0x00007ff2f5dd8d40>:0x00007ff2f5dd8b88>
Traceback (most recent call last):
	46: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `block in create_worker'
	45: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `catch'
	44: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `block (2 levels) in create_worker'
	43: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `loop'
	42: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:342:in `block (3 levels) in create_worker'
	41: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:353:in `run_task'
	40: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promise.rb:563:in `block in realize'
	39: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
	38: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
	37: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
	36: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
	35: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
	34: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
	33: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/base.rb:88:in `find_all_linked_assets'
	32: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bundler/gems/jekyll-assets-47fc845853e2/lib/jekyll/assets/patches/cached_environment.rb:37:in `block (2 levels) in <module:CachedEnvironment>'
	31: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/base.rb:81:in `find_asset'
	30: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
	29: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
	28: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
	27: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `block in load'
	26: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
	25: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
	24: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
	23: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
	22: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
	21: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/bundle.rb:27:in `call'
	20: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
	19: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
	18: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
	17: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `block in load'
	16: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
	15: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
	14: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
	13: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
	12: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
	11: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:33:in `call'
	10: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
	 9: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
	 8: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
	 7: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
	 6: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
	 5: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:31:in `call'
	 4: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:58:in `call'
	 3: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/utils.rb:138:in `module_include'
	 2: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sprockets-4.0.0/lib/sprockets/sassc_processor.rb:59:in `block in call'
	 1: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/sassc-2.2.1/lib/sassc/engine.rb:49:in `render'
/Users/me/Work/myblog/_assets/stylesheets/blocks/_hero.scss:13: Error: error in C function asset_path: undefined method `asset_path' for #<#<Class:0x00007ff2f5dd8d40>:0x00007ff2f5dd8b88> (SassC::SyntaxError)
        on line 13:21 of _assets/stylesheets/blocks/_hero.scss, in function `asset_path`
        from line 13:21 of _assets/stylesheets/blocks/_hero.scss, in mixin `@content`
        from line 62:7 of _assets/stylesheets/bootstrap/mixins/_breakpoints.scss, in mixin `media-breakpoint-up`
        from line 12:12 of _assets/stylesheets/blocks/_hero.scss
        from line 3:9 of _assets/stylesheets/homepage.scss
>>     background: url(asset_path('homepage-hero.png'));

   --------------------^
```

**Comment by envygeeks** [comment]
It looks like you're using master, please see if this bug exists on the stable version.

**Comment by envygeeks** [comment]
I say this because Jekyll Assets is undergoing a rewrite, and it's bound to be broken till I'm done.

**Comment by chalmagean** [comment]
I've tried going with the stable version but now I get a different exception. Not sure if it's related to jekyll-assets.

```
✗ jekyll b --trace
Configuration file: /Users/me/Work/myblog/_config.yml
            Source: /Users/me/Work/myblog
       Destination: /Users/me/Work/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2014-11-11-how-i-create-a-new-rails-project.md':
                    "\x89" from ASCII-8BIT to UTF-8
Traceback (most recent call last):
	33: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bin/ruby_executable_hooks:24:in `<main>'
	32: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bin/ruby_executable_hooks:24:in `eval'
	31: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bin/jekyll:23:in `<main>'
	30: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bin/jekyll:23:in `load'
	29: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	28: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	27: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	26: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	25: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	24: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	23: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	22: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	21: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	20: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	19: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
	18: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
	17: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
	16: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
	15: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:201:in `render'
	14: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `render_docs'
	13: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `each_value'
	12: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `block in render_docs'
	11: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `each'
	10: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
	 9: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
	 8: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
	 7: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:84:in `render_document'
	 6: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `convert'
	 5: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `reduce'
	 4: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `each'
	 3: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:102:in `block in convert'
	 2: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/converters/markdown.rb:85:in `convert'
	 1: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/cache.rb:109:in `getset'
/Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/cache.rb:88:in `[]': unhandled exception
	42: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bin/ruby_executable_hooks:24:in `<main>'
	41: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bin/ruby_executable_hooks:24:in `eval'
	40: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bin/jekyll:23:in `<main>'
	39: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/bin/jekyll:23:in `load'
	38: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	37: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	36: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	35: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	34: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	33: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	32: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	31: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	30: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	29: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	28: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
	27: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
	26: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
	25: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
	24: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:201:in `render'
	23: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `render_docs'
	22: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `each_value'
	21: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `block in render_docs'
	20: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `each'
	19: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
	18: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
	17: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
	16: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:84:in `render_document'
	15: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `convert'
	14: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `reduce'
	13: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `each'
	12: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:102:in `block in convert'
	11: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/converters/markdown.rb:85:in `convert'
	10: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/cache.rb:108:in `getset'
	 9: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/cache.rb:111:in `rescue in getset'
	 8: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/converters/markdown.rb:86:in `block in convert'
	 7: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/converters/markdown/kramdown_parser.rb:40:in `convert'
	 6: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/jekyll-4.0.0/lib/jekyll/converters/markdown/kramdown_parser.rb:40:in `new'
	 5: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/kramdown-2.1.0/lib/kramdown/document.rb:102:in `initialize'
	 4: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/kramdown-2.1.0/lib/kramdown/parser/base.rb:69:in `parse'
	 3: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/kramdown-parser-gfm-1.1.0/lib/kramdown/parser/gfm.rb:56:in `parse'
	 2: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/kramdown-2.1.0/lib/kramdown/parser/kramdown.rb:88:in `parse'
	 1: from /Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/kramdown-2.1.0/lib/kramdown/parser/base.rb:95:in `adapt_source'
/Users/me/.rvm/gems/ruby-2.6.3@myblog_jkl/gems/kramdown-2.1.0/lib/kramdown/parser/base.rb:95:in `encode': "\x89" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

**Comment by envygeeks** [comment]
It is not, we do not process or load any files not explicitly requested.

**Comment by chalmagean** [comment]
Unfortunately stable doesn't work with Jekyll 4. So I'm stuck.

**Comment by envygeeks** [comment]
Sorry I missed this @chalmagean, use a ref

```ruby
gem 'jekyll-assets', git: 'https://github.com/envygeeks/jekyll-assets.git', ref: 'ce5c8'
```

**Comment by chalmagean** [comment]
Thanks but I had to remove `jekyll-assets` from my site.
